import { NavLink } from 'react-router-dom';
import useRooms from '../../hooks/useRooms';
import EmptyState from '../ui/EmptyState';
import Spinner from '../ui/Spinner';

export default function RoomList({ onNavigate }) {
  const { rooms, isLoading, error } = useRooms();
  return <div className="flex h-full min-h-0 flex-col px-4 py-5"><NavLink to="/" onClick={onNavigate} className="px-3 text-[15px] font-bold tracking-[0.08em] text-brand">CONCLAVE</NavLink><div className="mt-9"><p className="px-3 text-[10px] font-bold uppercase tracking-[0.14em] text-muted">Workspace</p><nav className="mt-2 space-y-1"><NavLink end to="/" onClick={onNavigate} className={({ isActive }) => `block rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${isActive ? 'bg-brand-soft text-brand' : 'text-ink hover:bg-canvas'}`}>Home</NavLink><NavLink to="/notifications" onClick={onNavigate} className={({ isActive }) => `block rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${isActive ? 'bg-brand-soft text-brand' : 'text-ink hover:bg-canvas'}`}>Notifications</NavLink></nav></div><div className="mt-7 min-h-0 flex-1 overflow-y-auto"><div className="mb-2 flex items-center justify-between px-3"><h2 className="text-[10px] font-bold uppercase tracking-[0.14em] text-muted">Rooms</h2><span className="text-lg leading-none text-muted" aria-hidden="true">+</span></div>{isLoading && <Spinner label="Loading rooms" />}{error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}{!isLoading && !error && rooms.length === 0 && <EmptyState title="No rooms yet" description="Rooms you join will appear here." />}<nav className="space-y-1">{rooms.map((room) => <NavLink key={room.id} to={`/rooms/${room.id}`} onClick={onNavigate} className={({ isActive }) => `flex items-center gap-2.5 rounded-lg px-3 py-2.5 transition-colors ${isActive ? 'bg-brand-soft text-brand' : 'text-ink hover:bg-canvas'}`}><span className="grid h-7 w-7 shrink-0 place-items-center rounded-md bg-canvas text-xs font-semibold">#</span><span className="min-w-0"><span className="block truncate text-sm font-medium">{room.name}</span><span className="block text-[11px] text-muted">{room.member_count} members</span></span></NavLink>)}</nav></div><div className="border-t border-line px-3 pt-4"><NavLink to="/profile" onClick={onNavigate} className="block text-sm font-medium text-ink hover:text-brand">Your profile</NavLink><p className="mt-1 text-xs text-success">Online</p><NavLink to="/settings" onClick={onNavigate} className="mt-4 block text-sm font-medium text-muted hover:text-ink">Invite members</NavLink></div></div>;
}
